### ISSUE TITLE
Conversion doesn't work on some svg files

### ISSUE THREAD

**Issue by lightbringer1991** [NKjoep/svg-to-symbol#9]
Conversion fails on this file

[Details-icon.svg.zip](https://github.com/NKjoep/svg-to-symbol/files/1291784/Details-icon.svg.zip)

**Comment by NKjoep** [comment]
@lightbringer1991 I have to apologise with you. For some reason I didn't receive notification for this repo. 

Thank you for notifying me the issue, i'll have a look.

**Comment by NKjoep** [comment]
So looks like the conversion library doesn't like the `<style>` element.

Updating the svg from this:

```
<style type="text/css">
	.st0{fill:#333333;}
</style>

....

<path class="st0" ....

```


To this:

```
<path fill="#333333"
```

You'll get the right result.

**Comment by lightbringer1991** [comment]
@NKjoep is there a way to accommodate the style?
I'm happy to submit a PR if you like

**Comment by NKjoep** [comment]
Well, if you already know how to fix it, feel free to open a PR ;) 

I'll have a look at the issue in the next days.

**Comment by lightbringer1991** [comment]
I don't know yet, but will take a look
